# @format

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_db
    command: ['postgres', '-c', 'log_statement=all']
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
      - DATABASE_URL=postgres://postgres:postgres@postgres/chat_db
      - SERVER_DATABASES={postgres={url=postgres://postgres:postgres@postgres/chat_db}}
      - ENCRYPTION_KEY=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
    ports:
      - 8080:8080
    volumes:
      - ./chat-server:/app/chat-server
      - ./chat-common:/app/chat-common
    working_dir: /app/chat-server
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "diesel migration run && cargo watch --why -x run"
