# @format

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_db
    command: ['postgres', '-c', 'log_statement=all']
    ports:
      - '5432:5432'   

  server:
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8080
      - DATABASE_URL=postgres://postgres:postgres@postgres/chat_db
      - ROCKET_DATABASES={postgres={url=postgres://postgres:postgres@postgres/chat_db}}
    ports:
      - 8080:8080
    volumes:
      - ./chat-server:/app/chat-server
      - ./chat-common:/app/chat-common
    working_dir: /app/chat-server
    depends_on:
      - postgres

