# @format

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_db
    command: ['postgres', '-c', 'log_statement=all']
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chat-network
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - chat-network

  server:
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8001
      - DATABASE_URL=postgres://postgres:postgres@postgres/chat_db
      - |
        ROCKET_DATABASES={
        postgres={url=postgres://postgres:postgres@postgres/chat_db},
        redis={url=redis://redis:6379}
        }
      - ENCRYPTION_KEY=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
    ports:
      - 8080:8080
      - 8001:8001
    volumes:
      - ./chat-server:/app/chat-server
      - ./chat-common:/app/chat-common
    working_dir: /app/chat-server
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "diesel migration run && cargo watch --why -x run"
    networks:
      - chat-network

  frontend:
    build:
      context: ./chat-server-frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - API_BASE_URL=http://localhost:8001
    depends_on:
      - server
    networks:
      - chat-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - server
    networks:
      - chat-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  grafana-storage:
