[package]
edition = "2021"
name = "chat-server"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
chat-common = {path = "../chat-common"}
clap = {version = "4.0", features = ["derive"]}
serde_cbor = "0.11"
tracing = "0.1.41"
tracing-subscriber = "0.3"

[lib]
name = "chat_server"
path = "src/lib.rs"

[[bin]]
name = "chat-server"
path = "src/main.rs"
