[package]
edition = "2021"
name = "chat-server"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
chat-common = {path = "../chat-common"}
clap = {version = "4.0", features = ["derive"]}
serde_cbor = "0.11"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
